### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by martinoli-f** [DataAccess2020/Capstone_Gtrends_ITAElection#1]
- [x] control the comparison between party leaders' surnames
- [x] make sense to control also for the key "pd" in order to equilibrate the gap? ("pd" more searched than "letta")
- [x] fix the plots (adding title, labels, colour, etc.)
- [x] report structure: at first look at the hits of each key for each subject THEN look at the comparison between different subjects
- [x] edit dataframes  and save them into the folder "data"
- [x] compare means grouping by keywords
